/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f4',
        'surface-dim': '#e0d9d3',
        'surface-bright': '#fff8f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#faf2ed',
        'surface-container': '#f4ece7',
        'surface-container-high': '#eee7e1',
        'surface-container-highest': '#e9e1dc',
        'on-surface': '#1e1b18',
        'on-surface-variant': '#554336',
        'inverse-surface': '#33302c',
        'inverse-on-surface': '#f7efea',
        outline: '#887364',
        'outline-variant': '#dbc2b0',
        'surface-tint': '#904d00',
        primary: '#8d4b00',
        'on-primary': '#ffffff',
        'primary-container': '#b15f00',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#ffb77d',
        secondary: '#006c4a',
        'on-secondary': '#ffffff',
        'secondary-container': '#82f5c1',
        'on-secondary-container': '#00714e',
        tertiary: '#a83300',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#cc4815',
        'on-tertiary-container': '#fffbff',
        'primary-fixed': '#ffdcc3',
        'primary-fixed-dim': '#ffb77d',
        'on-primary-fixed': '#2f1500',
        'on-primary-fixed-variant': '#6e3900',
        'secondary-fixed': '#85f8c4',
        'secondary-fixed-dim': '#68dba9',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb59d',
        'on-tertiary-fixed': '#390c00',
        'on-tertiary-fixed-variant': '#832600',
        background: '#fff8f4',
        'on-background': '#1e1b18',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      maxWidth: {
        'app': '428px',
      }
    },
  },
  plugins: [],
}
